### ISSUE TITLE
Low Fidelity Prototype Images

### ISSUE THREAD

**Issue by spaceytato** [Tokolokopoko/Team-Toot#3]
This ticket covers creating images for the low fidelity prototype once the wireframe has been completed. It is dependent on the wireframe. 

### Tasks
- [ ] Look at existing mobile applications for similar services
- [ ] Establish Design Requirements
- [ ] Design Visual Prototype in Figma or Illustrator for presentation
